#!/usr/bin/env sh

SEMVER=`dotnet dotnet-gitversion -showvariable SemVer`

mkdir ./artifacts

npm version --git-tag-version false --allow-same-version true -- $SEMVER
npm install
npm run build:vsix -- -o ./artifacts/shebang-snippets-$SEMVER.vsix
