#!/usr/bin/env sh

dotnet tool restore
SEMVER=`dotnet dotnet-gitversion -showvariable SemVer`

mkdir ./artifacts

npm version --git-tag-version false --allow-same-version true -- $SEMVER
npm install @vscode/vsce -g
vsce package -o ./artifacts/shebang-snippets-$SEMVER.vsix
