#!/usr/bin/env bash

export DOTNET_NOLOGO=true
SEMVER=`dotnet dotnet-gitversion -showvariable SemVer`
PRERELEASETAG=`dotnet dotnet-gitversion -showvariable PreReleaseTag`
VSIX_FILENAME="artifacts/shebang-snippets-$SEMVER.vsix"

mkdir ./artifacts

npm version --git-tag-version false --allow-same-version true -- $SEMVER
if [[ -n "$PRERELEASETAG" ]]; then
   npm pkg set preview='true'
fi
pnpm install
pnpm build:vsix -- -o $VSIX_FILENAME
